### ISSUE TITLE
Requires Capability to utilise a predefined and instantiated Wire()

### ISSUE THREAD

**Issue by bryn51** [sciosense/ENS210_driver#3]
When the user has an environment that uses a non-standard wire port (perhaps an alternative one) It simpler just to pass in a reference to that wire instead of setting it up again inside the temperature sensor library.

I made a fork that contains an additional 'begin' to provide this functionality an initiated a pull request for you to include it in the main branch.

**Comment by bryn51** [comment]
SCIOSENSE have not responded to this issue

**Comment by webseitz** [comment]
We apologize for not responding on time. However, please check-out our new ENS21x library which solves this issue: https://github.com/sciosense/ENS21x_driver.
